name: Deploy

on:
  release:
    types:
      - published

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
          architecture: x64

      - name: Install Dependencies
        run: |
          pip install -U pip
          pip install -U wheel setuptools twine

      - name: Build Source Package
        run: |
          python setup.py sdist
          pip wheel -w wheelhouse .

      - name: Upload Package to PyPI
        run: |
          twine upload --repository testpypi --non-interactive dist/*.tar.gz wheelhouse/*.whl
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
